# User Defined Functions

Justin Post

In order to get the most out of any programming language, we need to understand how to write our own functions. User-Defined functions allow us to streamline our code, simplify large sections of code, and make our code easier to generalize to other situations.

## Function Creation Syntax

- To create our own functions, we just need to use the keyword `def`, give a function name with arguments, and then tab in (four spaces) our document body.

```
def function_name(arg1, arg2, arg3 = default_arg3):
    """
    Documentation string
    """
    Function body
    return object
```

Good programming practices indicates we should use a 'doc-string' to describe the purpose of the function directly after the function definition. This is usually done with a multi-line comment via triple quotes.

## Write Our Own Mean Function

We discussed common tasks for data. Of course one was simply describing a data set that we have. One way to describe the center of a variable's distribution is through the sample mean.

- Given data points labeled as $y_1, y_2, ..., y_n$ ($n$ is the number of observations), the sample mean is

$$\bar{y}=\frac{1}{n}\sum_{i=1}^{n}y_i$$

Let's write a function to calculate the mean of a `list` of numbers using the `sum()` and `len()` functions.


In [67]:
def find_mean(y):
    """
    Quick function to find the mean
    Assumes we have a list with only numeric type data
    """
    return sum(y)/len(y)

Now let's apply our function to a `list` of numeric values. We can create a sequence of values using the `range()` function. This function takes two arguments, the starting point and the ending point (which isn't included).

`range()` itself is a immutable *iterable* type object. It isn't the values themselves but an object that can be used to create the values. In the case of `range()` it [can be described as a *lazy* list](https://stackoverflow.com/questions/13092267/if-range-is-a-generator-in-python-3-3-why-can-i-not-call-next-on-a-range).

One way to get the `range()` object to create its values is by running `list()` on it. This tells python to iterate over the `range()` object and produce the numbers.

In [68]:
seq = range(0,11) #same as range(11)
seq #doesn't show values

range(0, 11)

In [69]:
list(seq)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [70]:
find_mean(list(seq))

5.0

Iterators (and iterator type objects) are often used to save memory as you often don't need the entire sequence, but do want to use them in some kind of order.

---

## Add Argument with Default

Often we want to give default arguments to our function. That is, arguments that are used unless the user specifies something else.

- Suppose we want to add in a **trimmed mean** functionality
- This is a mean where we first remove the smallest p% of values and the largest p% of values. We then take the mean of the remaining numbers.
- A trimmed mean is more **robust** to outliers. For instance,

In [71]:
find_mean([1,2,3,4,5,100]) #the mean is greatly affected by the large value

19.166666666666668

In [72]:
find_mean([1,2,3,4,5]) #remove the large value to get a better idea about 'most' of the data values

3.0

To create a trimmed mean function (or option at least), we need to do the following:

- Sort the observations
- Remove the lowest p% and highest p%
- Find mean on the remaining values


In [73]:
#can pull in the floor and sqrt functions from math to help us out
from math import floor, sqrt
#generate 50 random values from the standard normal distribution
import numpy as np
y = np.random.default_rng(1).standard_normal(50)
#convert to a list just so we are working with an object we've studied
y = list(y)
y[0:10]

[0.345584192064786,
 0.8216181435011584,
 0.33043707618338714,
 -1.303157231604361,
 0.9053558666731177,
 0.4463745723640113,
 -0.5369532353602852,
 0.5811181041963531,
 0.36457239618607573,
 0.294132496655526]

Note that lists have a `.sort()` method but this modifies the list in place. Instead we can use the `sorted()` function which returns a new sorted version of the list.

In [107]:
sort_y = sorted(y)
print(sort_y[0:10])
print(y[0:10])

[-2.7111624789659685, -1.8890132459676727, -1.6480751708556527, -1.303157231604361, -1.2273520542445742, -1.1120207626922813, -0.9447516230607774, -0.7819084623568421, -0.7364540870016669, -0.6832266617805622]
[0.345584192064786, 0.8216181435011584, 0.33043707618338714, -1.303157231604361, 0.9053558666731177, 0.4463745723640113, -0.5369532353602852, 0.5811181041963531, 0.36457239618607573, 0.294132496655526]


Now, given a value of p, we can remove the lowest and high p% of values. We can do this with the `floor()` function. This gives us the largest interger below a given value.

In [75]:
print(floor(4))
print(floor(4.2))
print(floor(4.9))

4
4
4


Given a p (for proportion) we can determine the number of observations corresponding to that proportion using the length of `y`.

In [108]:
p = 0.11
print(p*len(sort_y))
to_remove = floor(p*len(sort_y))
to_remove

5.5


5

We can remove observations by simply subsetting our list using the `:` operator we studied. Remember that this operator doesn't include the **last** value. (i.e. `2:5` gives `2`, `3`, `4`)

In [109]:
print([to_remove, len(sort_y)-to_remove])#values we want to keep are between these
#remember, counting starts at 0
#we want the remove the first 5 values so we should start with the 5th index (the 6th actual value!)
#with a length 50 list, we want to remove the 46-50th elements which correspond to the 45-49 indices
#since we don't include our last index, we can end on 45
sort_y[to_remove:(len(sort_y)-to_remove)]

[5, 45]


[-1.1120207626922813,
 -0.9447516230607774,
 -0.7819084623568421,
 -0.7364540870016669,
 -0.6832266617805622,
 -0.5369532353602852,
 -0.5140063716874629,
 -0.5062916583143148,
 -0.48211931267997826,
 -0.42219041157635356,
 -0.37760500712699807,
 -0.2924567509650886,
 -0.2756029052993704,
 -0.2571922406188707,
 -0.17477209205516195,
 -0.16290994799305278,
 -0.09826996785221727,
 -0.07204367972722743,
 0.008142180518343508,
 0.02842224131579679,
 0.03558623705548571,
 0.03972210748165899,
 0.09548302746945433,
 0.10901408782154753,
 0.16746474422274113,
 0.2136429974986111,
 0.21732193102256359,
 0.294132496655526,
 0.33043707618338714,
 0.345584192064786,
 0.36457239618607573,
 0.4463745723640113,
 0.5467129866124469,
 0.5811181041963531,
 0.5937480717858228,
 0.5988462126346276,
 0.6467029962018469,
 0.6630633723762617,
 0.8216181435011584,
 0.8911669542823284]

### Modify the function arguments

Now that we have the process down (this is a good way to write functions by the way, write them outside of a function first and then put the pieces into the function), we can add our arguments/calculations.

We'll add a
- `method =` argument with a default value of `None`. `None` is a special name that defines no value.
    + If this argument takes on `Trim`, we'll do a trimmed mean.
    + This can be done using `if Boolean:` with the resulting code to execute tabbed in four spaces
- a `p =` argument to specify the proportion to remove with a default value set to 0.


In [114]:
def find_mean(y, method = None, p = 0):
    """
    Quick function to find the mean
    Assumes we have a list with only numeric type data
    If method is set to Trim, will remove outer most p values off the data
    before finding the mean
    """
    if method == "Trim": #we'll cover if shortly! The indented code only runs if this condition is met
      sort_y = sorted(y)
      to_remove = floor(p*len(sort_y))
      y = sort_y[to_remove:(len(sort_y)-to_remove)] #replace y with the modified version
    return sum(y)/len(y)

Let's test the function!

In [115]:
find_mean(y, method = "Trim", p = 0) #usual mean

-0.03607807742830818

In [116]:
find_mean(y, method = "Trim", p = 0.05) #5% trimmed mean

-0.029659532804894563

In [117]:
find_mean(y, method = "trim", p = 0.05) #mean not trimmed if method not set correctly

-0.03607807742830817

---

## Positional vs Named Arguments

- A function can be called using positional or named args

In [118]:
#def find_mean(y, method = None, p = 0):
print(find_mean(y, None))
print(find_mean(method = "Trim", p = 0.1, y = y))
print(find_mean(y, "Trim", 0.1))

-0.03607807742830817
-0.009797451217442077
-0.009797451217442077


- You can't place positional args after a keyword though!

In [119]:
find_mean(y = x, "Trim")

SyntaxError: positional argument follows keyword argument (<ipython-input-119-39dc4eceb262>, line 1)

## Defining the Type of Argument

- A function definition may look like:
```
def f(pos1, pos2, /, pos_or_kwd, *, kwd1, kwd2):
           -----------    ----------     ----------
           |              |                  |
           |         Positional or keyword   |
           |                                 - Keyword only
           -- Positional only
```

In [120]:
def print_it(x, y, /):
    print("Must pass x and y positionally!" + x + y)

def print_it(x, /, y):
    print("x must be passed positionally.  y can be positional or named" + x + y)

def print_it(x, /, y, *, z):
    print("Now z must be passed as a named argument" + x + y + z)

Let's modify our mean function and show this.

In [123]:
#with this, y must be passes positionally!
def find_mean(y, /, method = None, p = 0):
    """
    Quick function to find the mean
    Assumes we have a list with only numeric type data
    If method is set to Trim, will remove outer most p values off the data
    before finding the mean
    """
    if method == "Trim": #we'll cover if shortly! The indented code only runs if this condition is met
      sort_y = sorted(y)
      to_remove = floor(p*len(sort_y))
      y = sort_y[to_remove:(len(sort_y)-to_remove)] #replace y with the modified version
    return sum(y)/len(y)

In [124]:
find_mean(y, "Trim", p = 0.1)


-0.009797451217442077

In [125]:
find_mean(y = y, method = "Trim", p = 0.1) #this won't work!

TypeError: find_mean() got some positional-only arguments passed as keyword arguments: 'y'

---

## Write Our Own Correlation Function

Just to demonstrate something more complicated, let's write our own function to compute the (usual) sample correlation between two variables, call them `x` and `y`.

- Pearson's correlation:

$$r = \frac{\sum_{i=1}^{n}(x_i-\bar{x})(y_i-\bar{y})}{\sqrt{\sum_{i=1}^n(x_i-\bar{x})^2\sum_{i=1}^{n}(y_i-\bar{y})^2}}$$

where
- $(x_i, y_i)$ are numeric variables observed on the same $n$ units, $i=1,...,n$

### Plan

Function inputs:
- $x$, $y$, **lists** with numeric entries only

Function body:
- Find sample means for $x$ and $y$
- Compute numerator sum and denominator sums
- Find quotient and return that value


#### Finding Means

In [126]:
x = list(range(1,51))
print(x[1:10])
xbar = find_mean(x)
xbar

[2, 3, 4, 5, 6, 7, 8, 9, 10]


25.5

In [127]:
#use same y as before
y = list(np.random.default_rng(1).standard_normal(50))
print(y[1:10])
ybar = find_mean(y)
ybar

[0.8216181435011584, 0.33043707618338714, -1.303157231604361, 0.9053558666731177, 0.4463745723640113, -0.5369532353602852, 0.5811181041963531, 0.36457239618607573, 0.294132496655526]


-0.03607807742830817

These two vectors are not related and should have a near 0 correlation!

Next, we need to find the numerator and denominator sums. Finding the sums will be easier once we learn arrays, but for now we'll peak at a `for` loop and the `zip()` function.

Let's start with computation of
$$\sum_{i=1}^n(x_i-\bar{x})^2$$


In [128]:
#computation in one of our sums (we want this across all 50 values, then added up)
(x[0]-xbar)**2

600.25

So really we want to find all of these values:
```
(x[0]-xbar)**2
(x[1]-xbar)**2
...
(x[49]-xbar)**2
```
We can use `for` to iterate over the values of 0, 1, ..., 49. Similar to function definitions and `if` statements, we just tab in (four spaces) the code to be executed at each iteration of the for loop.

In [129]:
#initialize a value to store the sum in
den_x = 0
#use a for loop to iterate across values (studies more later!)
for i in x:
    den_x += (i-xbar)**2
den_x

10412.5

We can very easily get a similar computation for $y$'s portion of the denominator.

To get the numerator, that's a bit more work. We really need to find
```
(x[0]-xbar)(y[0]-ybar)
(x[1]-xbar)(y[1]-ybar)
...
(x[49]-xbar)(y[49]-ybar)
```

We can `zip()` the $x$ and $y$ lists together. This essentially just pairs the 0th elements, the 1st elements, etc.  Then we can iterate over the values together.

In [130]:
num = 0
for i, j in zip(x, y):
    num += (i-xbar)*(j-ybar)
num

-51.69981003655184

Ok, now we are ready to put these together and calculate our correlation!


In [131]:
def find_corr(x, y):
    """
    Compute Pearson's Correlation Coefficient
    x and y are assumed to be lists with numeric values
    Data is assumed to have no missing values
    """
    xbar = find_mean(x)
    ybar = find_mean(y)
    num = 0
    den_x = 0
    den_y = 0
    for i, j in zip(x, y):
        num +=(i-xbar)*(j-ybar)
        den_x +=(i-xbar)**2
        den_y +=(j-ybar)**2
    return num/sqrt(den_x*den_y)

Let's test our function on our data!

In [133]:
find_corr(x, y) #near 0!

-0.0813179110596017

Note that all functions with a doc string have a `.__doc__` attribute that you can look at to understand that function (assuming the doc string is useful!).

In [134]:
print(find_corr.__doc__)


    Compute Pearson's Correlation Coefficient
    x and y are assumed to be lists with numeric values
    Data is assumed to have no missing values
    


In [135]:
print(len.__doc__) #another example on a common function

Return the number of items in a container.


In [136]:
print(np.random.default_rng.__doc__) #another example

Construct a new Generator with the default BitGenerator (PCG64).

    Parameters
    ----------
    seed : {None, int, array_like[ints], SeedSequence, BitGenerator, Generator}, optional
        A seed to initialize the `BitGenerator`. If None, then fresh,
        unpredictable entropy will be pulled from the OS. If an ``int`` or
        ``array_like[ints]`` is passed, then it will be passed to
        `SeedSequence` to derive the initial `BitGenerator` state. One may also
        pass in a `SeedSequence` instance.
        Additionally, when passed a `BitGenerator`, it will be wrapped by
        `Generator`. If passed a `Generator`, it will be returned unaltered.

    Returns
    -------
    Generator
        The initialized generator object.

    Notes
    -----
    If ``seed`` is not a `BitGenerator` or a `Generator`, a new `BitGenerator`
    is instantiated. This function does not manage a default global instance.
    
    Examples
    --------
    ``default_rng`` is the recommended 

## Other Things to Note

- When executing a function, a new symbol table is used for the local variables
- This keeps us from accidentally overwriting something

In [138]:
import numpy as np
y = np.array(range(1,11))

def square(z):
    y = z**2
    print("In the function environment, z = " + str(z) + " and y = " + str(y))
    return(y)

print(square(y))
print(y)

In the function environment, z = [ 1  2  3  4  5  6  7  8  9 10] and y = [  1   4   9  16  25  36  49  64  81 100]
[  1   4   9  16  25  36  49  64  81 100]
[ 1  2  3  4  5  6  7  8  9 10]


In [139]:
print(z) #z isn't defined outside the function call!

NameError: name 'z' is not defined

- You can define global variables in a function using `global`

In [140]:
def square(z):
    global y
    y = z**2
    print("In the function environment, z = " + str(z) + " and y = " + str(y))
    return(y)

print(square(y))
print(y) #modified globally now

In the function environment, z = [ 1  2  3  4  5  6  7  8  9 10] and y = [  1   4   9  16  25  36  49  64  81 100]
[  1   4   9  16  25  36  49  64  81 100]
[  1   4   9  16  25  36  49  64  81 100]


- If nothing is returned from a function (with `return`) then it actually returns the special `None`

In [141]:
def square_it(a):
    if (type(a) == int) or (type(a) == float):
      return a**2
    else:
      return

print(square_it(10))
print(square_it(10.5))
print(square_it("10"))

100
110.25
None
None


- Default values are only evaluated once - at the time of the function **definition**

- Mutable objects can cause an issue! (Lists are mutable as they can be changed, some objects, like tuples, are immutable and can't be modified.)

In [143]:
#append a value to a list but give a default empty list if not given
def my_append(value, L = []):
    L.append(value)
    return L

#correctly appends "A" to the list
print(my_append("A"))
#appends "B" to the previous list as L = [] was only evaluated at the time the function was created!
print(my_append("B"))

['A']
['A', 'B']


- To avoid this behavior, instead define the default value as `None` and take care of things within the function body

In [144]:
def my_append(value, L = None):
    if L is None:
        L = []
    L.append(value)
    return L

print(my_append("A"))
print(my_append("B"))

['A']
['B']


## Video Demo

This quick video demo gives another example of creating our own function! (Coming soon)


---

# Recap

- Writing functions is super cool!

In [ ]:
def func_name(args):
    """
    Doc string
    """
    body
    return object

- Many ways to set up your function arguments and to call your function

- Even more on function writing will be covered later!
